Improve mntold to load LVM / detect root
git-svn-id: http://ns2.distrotech.co.za/svnsrc/distrotech-core/trunk@1116 a03fbada-158d-47ef-9f12-77e997805b15

diff --git a/usr/sbin/mntold b/usr/sbin/mntold
--- a/usr/sbin/mntold
+++ b/usr/sbin/mntold
@@ -1,32 +1,73 @@
 #!/bin/bash
 
-if [ "$1" ];then
-  mount $1 /mnt -o ro
+MPNT=/mnt
+
+(vgscan
+vgchange -a y) > /dev/null
+
+if [ "${1}" ];then
+  root=${1}
+ elif [ -e /dev/lvm/root ];then
+  root=/dev/lvm/root
+ else
+  root=`findfs LABEL=root 2>/dev/null`
+fi;
+
+if [ ! "${root}" ];then
+  echo "No root device specified"
+  exit -1
+fi;
+
+mount ${root} ${MPNT} -o ro
+if [ $? != 0 ];then
+  echo "Mount failed"
+  exit -1
+fi;
+
+for bind in dev proc sys;do
+  mount --bind /${bind} ${MPNT}/${bind}
+done;
+
+chroot ${MPNT} fsck -TCAa
+RES=$?
+if (( ${RES} >= 2 )) && (( ${RES} != 32 ));then
+  for bind in dev proc sys;do
+    umount ${MPNT}/${bind}
+  done;
+  umount ${MPNT}
+  echo "FILE SYSTEM ERROR"
+  if [ ${RES} == 2 ];then
+    echo "REBOOT REQUIRED"
+  fi;
+  exit ${RES}
+fi;
+
+mount ${MPNT} -o remount,rw
+rm ${MPNT}/etc/mtab
+touch ${MPNT}/etc/mtab
+chroot ${MPNT} mount -f /
+chroot ${MPNT} swapon -a
+chroot ${MPNT} mount -a
+if [ -e ${MPNT}/etc/HOSTNAME ];then
+  cp ${MPNT}/etc/hosts ${MPNT}/etc/resolv.conf /etc
+  hostname -F ${MPNT}/etc/HOSTNAME
+fi;
+
+UDEV=`findfs LABEL=UPGRADE`;
+if [ ${UDEV} ];then
+  mount ${UDEV} ${MPNT}/mnt/update -o ro
   if [ $? == 0 ];then
-    for bind in dev proc sys;do
-      mount --bind /${bind} /mnt/${bind}
-    done;
-    chroot /mnt fsck -A -p
-    mount /mnt -o remount,rw
-    rm /mnt/etc/mtab
-    touch /mnt/etc/mtab
-    chroot /mnt mount -f /
-    chroot /mnt swapon -a
-    chroot /mnt mount -a -t ext2,ext3,ext4,vfat
-    if [ -e /mnt/etc/HOSTNAME ];then
-      cp /mnt/etc/hosts /mnt/etc/resolv.conf /etc
-      hostname -F /mnt/etc/HOSTNAME
+    mount --bind / ${MPNT}/mnt/update/mnt/dev -o ro
+    if [ -e ${MPNT}/var/run/rsyncd.pid ];then
+      rm ${MPNT}/var/run/rsyncd.pid
     fi;
-    UDEV=`findfs LABEL=UPGRADE`;
-    if [ ${UDEV} ];then
-      mount ${UDEV} /mnt/mnt/update
-      mount --bind / /mnt/mnt/update/mnt/dev
-      if [ -e /mnt/var/run/rsyncd.pid ];then
-        rm /mnt/var/run/rsyncd.pid
-      fi;
-      chroot /mnt rsync --daemon --config /etc/rsyncd-update.conf
-    fi;
-   else
-    echo "Mount failed"
+    chroot ${MPNT} rsync --daemon --config /etc/rsyncd-update.conf
   fi;
 fi;
+
+#chroot ${MPNT}
+#while [ "`pidof rsync`" ];do
+#  killall rsync
+#  sleep 2
+#done;
+#awk '/.* \/mnt/ {printf "%s:%s\n",length($2),$2}' /proc/mounts |sort -nr |awk -F: '{printf "umount %s\n",$2}' |sh
